<#
  Local def-name resolution for ppcli.ps1.

  A plain word an agent already knows ("crabman") becomes the exact def name a plan needs
  ("Crabman_Gunner_TacCharacterDef") WITHOUT a live def hunt and without re-deriving names from the
  decompile. Everything here is offline: it reads catalog\aliases.ndjson (curated, committed) and
  catalog\defs.ndjson (generated by `ppcli.ps1 index` against a running game).

  Dot-sourced by ppcli.ps1 and by tests\resolve-names.tests.ps1 - it defines functions and runs
  nothing, which is what makes the resolver testable with no game.
#>

# Only these plan vars name a def. Every other var is passed through untouched. `weaponDef` and
# `enemyDef` are weapon-test.json's: one plan needs to name TWO defs at once, so `defName`/`itemName`
# are not enough, and resolving them here is also where "PX_AssaultRifle" gets REFUSED for matching
# both the rifle and its ammo clip - locally, before a run measures the wrong weapon.
$script:PPCLI_VarFamily = @{
    defName    = 'actor'
    itemName   = 'item'
    researchId = 'research'
    enemyDef   = 'actor'
    weaponDef  = 'item'
}

function Write-PPNote([string] $m) { [Console]::Error.WriteLine($m) }

<#
  Def TYPE name -> catalog family. Derived from the type, never a hand-maintained list of def names.
  Ordered: the first rule that holds wins, so ResearchDef is decided before the item rules and
  everything unclaimed lands in 'other'.
#>
function Get-DefFamily([string] $typeName) {
    if (-not $typeName) { return 'other' }
    switch -Regex ($typeName) {
        'TacCharacterDef$|TacActorDef$|ActorDef$' { return 'actor' }
        'ResearchDef$'                            { return 'research' }
        'StatusDef$'                              { return 'status' }
        'MissionTypeDef$'                         { return 'mission-type' }
        'PlotDef$|MapDef$'                        { return 'map-plot' }
        'WeaponDef$|AmmoDef$|ItemDef$|EquipmentDef$' { return 'item' }
    }
    return 'other'
}

# One curated alias file, read whole - it is hand-written and small, unlike defs.ndjson.
function Get-AliasRows([string] $CatalogDir) {
    $path = Join-Path $CatalogDir 'aliases.ndjson'
    if (-not (Test-Path $path)) { return @() }
    $rows = @()
    foreach ($line in [IO.File]::ReadLines($path)) {
        if ([string]::IsNullOrWhiteSpace($line) -or $line.TrimStart().StartsWith('#')) { continue }
        try { $rows += ($line | ConvertFrom-Json) } catch { Write-PPNote "aliases.ndjson: skipping unparseable line" }
    }
    # Returned bare, wrapped in @() by the caller: a `,$rows` here nests the array one level deeper
    # than @() unwraps, which silently turns "0 hits" and "2 hits" both into "1 hit".
    return $rows
}

<#
  Streams defs.ndjson line by line and keeps the rows of this family whose def name (or, for
  research, whose id) contains the needle. The catalog is tens of thousands of lines, so it is never
  read into memory as one object; the cheap ordinal contains-check on the RAW line is what keeps
  ConvertFrom-Json off the 99% of lines that cannot match.
#>
function Find-CatalogRows([string] $DefsPath, [string] $Needle, [string] $Family) {
    $hits = @()
    foreach ($line in [IO.File]::ReadLines($DefsPath)) {
        if ($line.IndexOf($Needle, [StringComparison]::OrdinalIgnoreCase) -lt 0) { continue }
        $r = $null
        try { $r = $line | ConvertFrom-Json } catch { continue }
        if ($r.f -ne $Family) { continue }
        # The raw-line check also matches the type field; the real test is the name (or the id).
        $inName = $r.n -and $r.n.IndexOf($Needle, [StringComparison]::OrdinalIgnoreCase) -ge 0
        $inId   = $r.id -and $r.id.IndexOf($Needle, [StringComparison]::OrdinalIgnoreCase) -ge 0
        if ($inName -or $inId) { $hits += $r }
    }
    return $hits
}

# What a plan must actually be given: GetResearchById matches ResearchDef.Id (Research.cs:763-765,
# ResearchElement.cs:221), which is NOT the def name. Everything else is named by its def name.
function Get-RowValue($row) {
    if ($row.f -eq 'research' -and $row.id) { return [string]$row.id }
    return [string]$row.n
}

<#
  The EXACT arm of resolution. A def NAME outranks a research id: the catalog really does hold
  CopyOfPX_PandoraKey_ResearchDef whose id is PX_PandoraKey_ResearchDef, so one input can match two
  rows exactly and taking whichever came first is a silent wrong research the day the copy gets its
  own Id. Two DISTINCT surviving values refuse; two rows agreeing on one value are one answer.
  Returns $null when nothing matches exactly.
#>
function Get-ExactValue($hits, [string] $Value, [string] $Family) {
    $chosen = @($hits | Where-Object { ([string]$_.n) -ieq $Value })
    if ($chosen.Count -eq 0) { $chosen = @($hits | Where-Object { $_.id -and ([string]$_.id) -ieq $Value }) }
    if ($chosen.Count -eq 0) { return $null }
    $values = @($chosen | ForEach-Object { Get-RowValue $_ } | Select-Object -Unique)
    if ($values.Count -gt 1) {
        throw ("REFUSED: '$Value' matches $($values.Count) DISTINCT $Family defs exactly (" +
               ($values -join ', ') + ') - name the one you mean.')
    }
    [string]$values[0]
}

# defs.ndjson and meta.json are written by two separate moves, so a run that died between them leaves
# new rows described by stale metadata. The row count is the one field that can catch that from here.
# A catalog with no meta.json predates the check and is taken as given.
function Assert-CatalogIntact([string] $CatalogDir, [string] $DefsPath) {
    $metaPath = Join-Path $CatalogDir 'meta.json'
    if (-not (Test-Path $metaPath)) { return }
    $meta = $null
    try { $meta = Get-Content -Raw $metaPath | ConvertFrom-Json } catch { }
    if ($null -eq $meta -or $null -eq $meta.rows) { return }
    $lines = 0
    foreach ($line in [IO.File]::ReadLines($DefsPath)) { if (-not [string]::IsNullOrWhiteSpace($line)) { $lines++ } }
    if ($lines -ne [int]$meta.rows) {
        throw ("REFUSED: the def catalog is STALE - $metaPath says $($meta.rows) rows but $DefsPath has $lines. " +
               "Re-run '.\ppcli.ps1 index' against a running game.")
    }
}

<#
  intent -> exact def name. Deterministic precedence, no fuzzy scoring:
    exact def name (or exact research id) -> exact alias -> UNIQUE substring -> REFUSE.
  Ambiguity always refuses with the candidates on stderr; guessing here would spawn the wrong
  creature into a real save. A missing catalog is a WARNING and a pass-through, never a hard fail:
  an already-exact def name must keep working before anyone has ever run `ppcli.ps1 index`.
#>
function Resolve-DefValue {
    param(
        [Parameter(Mandatory = $true)] [string] $VarName,
        [string] $Value,
        [Parameter(Mandatory = $true)] [string] $CatalogDir
    )

    $family = $script:PPCLI_VarFamily[$VarName]
    if (-not $family) { return $Value }
    if ([string]::IsNullOrWhiteSpace($Value)) { return $Value }

    # The alias is FOUND here but not applied yet: aliases.ndjson is hand-edited and unvalidated, so a
    # casual name that happens to equal a real def name must not steer a correct exact input elsewhere.
    # The exact def name wins; the alias is the fallback.
    $aliasRow = $null
    foreach ($row in @(Get-AliasRows $CatalogDir)) {
        if ($row.f -ne $family) { continue }
        $names = @($row.a) + @($row.n)
        if ($names | Where-Object { $_ -and ([string]$_) -ieq $Value }) { $aliasRow = $row; break }
    }

    $defs = Join-Path $CatalogDir 'defs.ndjson'
    if (-not (Test-Path $defs)) {
        if ($aliasRow -and [string]$aliasRow.n -ne $Value) {
            Write-PPNote "$VarName '$Value' -> '$($aliasRow.n)' (alias)"
            $Value = [string]$aliasRow.n
        }
        Write-PPNote ("no def catalog at $defs - '$Value' is sent as given. " +
                      "Run '.\ppcli.ps1 index' once against a running game to build it.")
        return $Value
    }
    Assert-CatalogIntact $CatalogDir $defs

    $aliased = $false
    $hits = @(Find-CatalogRows $defs $Value $family)
    $exact = Get-ExactValue $hits $Value $family
    if ($null -ne $exact) {
        if ($aliasRow -and [string]$aliasRow.n -ne $Value) {
            Write-PPNote ("COLLISION: '$Value' is an alias for '$($aliasRow.n)' AND a real $family def name - " +
                          'the exact def name wins. Rename the alias in aliases.ndjson.')
        }
        return $exact
    }

    if ($aliasRow -and [string]$aliasRow.n -ne $Value) {
        Write-PPNote "$VarName '$Value' -> '$($aliasRow.n)' (alias)"
        $Value = [string]$aliasRow.n
        $aliased = $true
        $hits = @(Find-CatalogRows $defs $Value $family)
        $exact = Get-ExactValue $hits $Value $family
        if ($null -ne $exact) { return $exact }
    }
    elseif ($aliasRow) { $aliased = $true }

    if ($hits.Count -eq 1) {
        $resolved = Get-RowValue $hits[0]
        Write-PPNote "$VarName '$Value' -> '$resolved' (unique $family match)"
        return $resolved
    }

    if ($hits.Count -eq 0) {
        # A curated alias the catalog does not know is a STALE catalog, not a bad request - send the
        # name and let the game answer. An un-aliased miss is the caller's typo and is refused.
        if ($aliased) {
            Write-PPNote "alias target '$Value' is not in $defs (stale catalog?) - sending it as given"
            return $Value
        }
        throw ("REFUSED: no $family def matching '$Value' in $defs. " +
               "Add an alias to catalog\aliases.ndjson, or pass the exact def name.")
    }

    $shown = ($hits | Select-Object -First 20 | ForEach-Object { Get-RowValue $_ })
    Write-PPNote ("candidates for '$Value': " + ($shown -join ', ') +
                  $(if ($hits.Count -gt 20) { " ... and $($hits.Count - 20) more" } else { '' }))
    throw "REFUSED: '$Value' matches $($hits.Count) $family defs - name one exactly, or add an alias."
}
